export PATH=/usr/local/bin:$PATH
# export PATH=/usr/local/share/python:$PATH
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Tell ls to be colourful
export CLICOLOR=1

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

source ~/.dotfiles/git/git-prompt.sh
#if [ -f `brew --prefix`/etc/bash_completion ]; then
#. `brew --prefix`/etc/bash_completion
#fi

# vi mode
set -o vi

# increase open file limit 
#ulimit -n 4096

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/code
source /usr/local/share/python/virtualenvwrapper.sh

#export PS1="\w\$(__git_ps1) \$ "
export PS1="\n\w\$(__git_ps1) \$ "

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

if [ -f ~/.bashrc ]; then 
    source ~/.bashrc 
fi
